### ISSUE TITLE
feat: use containrrr/watchtower instead of crontab

### ISSUE THREAD

**Issue by mscurtescu** [farcasterxyz/hub-monorepo#1645]
**What is the feature you would like to implement?**

Use the [containrrr/watchtower](https://github.com/containrrr/watchtower) docker service for image updates instead of `crontab`.

**Why is this feature important?**

- Hubble through docker compose is self sufficient, no need for `crontab` functionality in the host OS.
- Watchtower offers more functionality that just  automatic updates:
  -  notifications
  - upgrade multiple images
  - monitor only
- `hubble.sh` and the install process can be simplified

**Will the protocol spec need to be updated??**

No, not protocol related.

**How should this feature be built? (optional)**

Add one more service to docker compose.

As simple as:
```yaml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: hubble --interval 3600
```

**Additional context**

Watchtower documentation: https://containrrr.dev/watchtower/
