### ISSUE TITLE
feat: add docker heath checks to services

### ISSUE THREAD

**Issue by mscurtescu** [farcasterxyz/hub-monorepo#1646]
**What is the feature you would like to implement?**

For each service in `docker-compose.yml` add a `healtcheck` entry.

**Why is this feature important?**

- docker can restart non responding services
- docker has a reliable way to determine when a service is fully running on startup

**Will the protocol spec need to be updated??**

No, there are no protocol changes.

**How should this feature be built? (optional)**

```yaml
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost/health"]
  interval: 1m30s
  timeout: 10s
  retries: 3
  start_period: 2m
```

For details see:
https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

Hubble might require a `/health` endpoint.

**Additional context**

Graphana health check command:

```yaml
services:
  grafana:
    image: grafana/grafana:10.0.3
    ...
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health"]
```
